---
language: php
os:
- linux
- osx
php:
- 5.3
- 5.4
- 5.5
- 5.6
before_script:
- sudo apt-get update > /dev/null
- sudo apt-get install -qq unzip expect graphviz libmagickwand-dev
- expect ./build/tools/tools.expect
- cd build && ./getTools.sh && cd ..
- phpenv rehash
- php ./composer.phar install
- php ./composer.phar update

matrix:
  allow_failures:
  - php: 5.6
  - os: osx
script:
- ant travis -Dphpunit.testdox=true -Dpackage.version.patch=$TRAVIS_BUILD_NUMBER