---
language: php

os:
- linux

php:
- 5.6
- 7.0

before_install:
- pip install --user codecov

before_script:
- composer self-update
- composer install
- wget -nc -O ./phpunit.phar --no-check-certificate https://phar.phpunit.de/phpunit.phar
- chmod 755 ./phpunit.phar
- wget -nc -O ./phpcs.phar --no-check-certificate https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
- chmod 755 ./phpcs.phar
- phpenv rehash

matrix:
  allow_failures:
  - php: 7.0
  
script:
- rm -rf ./build
- php ./phpcs.phar
- php ./phpunit.phar --testdox -c ./phpunit.xml.dist

after_success:
- codecov